module.exports = {
	"rules": {
		/* eslint-enable sort-keys */
		"accessor-pairs": "off",
		"array-bracket-newline": "off",
		"array-bracket-spacing": "off",
		"array-callback-return": "off",
		"array-element-newline": "off",
		"arrow-body-style": "off",
		"arrow-parens": ["error", "always"],
		"arrow-spacing": ["error", {
			"before": true,
			"after": true
		}],
		"block-scoped-var": "off",
		"block-spacing": "off",
		"brace-style": "error",
		"callback-return": "off",
		"camelcase": ["error", {
			"properties": "never"
		}],
		"capitalized-comments": "off",
		"class-methods-use-this": "off",
		"comma-dangle": ["error", "never"],
		"comma-spacing": ["error", {
			"before": false,
			"after": true
		}],
		"comma-style": ["error", "last"],
		"complexity": "off",
		"computed-property-spacing": ["error", "never"],
		"consistent-return": "off",
		"consistent-this": "off",
		"constructor-super": "error",
		"curly": "error",
		"default-case": "off",
		"dot-location": "off",
		"dot-notation": "off",
		"eol-last": ["error", "always"],
		"eqeqeq": "error",
		"for-direction": "off",
		"func-call-spacing": ["error", "never"],
		"func-name-matching": "off",
		"func-names": "off",
		"func-style": "off",
		"generator-star-spacing": "off",
		"global-require": "off",
		"guard-for-in": "error",
		"handle-callback-err": "error",
		"id-blacklist": "off",
		"id-length": "off",
		"id-match": "off",
		"indent": ["error", "tab"],
		"indent-legacy": "off",
		"init-declarations": "off",
		"jsx-quotes": "off",
		"key-spacing":  ["error", {
			"afterColon": true,
			"beforeColon": false,
			"mode": "strict"
		}],
		"keyword-spacing": ["error", {
			"before": true
		}],
		"line-comment-position": "off",
		"linebreak-style": ["error", "unix"],
		"lines-around-comment": "off",
		"lines-around-directive": "off",
		"max-depth": "off",
		"max-len": "off",
		"max-lines": "off",
		"max-nested-callbacks": "off",
		"max-params": "off",
		"max-statements": "off",
		"max-statements-per-line": "off",
		"multiline-ternary": "off",
		"new-cap": "off",
		"new-parens": "error",
		"newline-after-var": "off",
		"newline-before-return": "off",
		"newline-per-chained-call": "off",
		"no-alert": "off",
		"no-array-constructor": "error",
		"no-await-in-loop": "off",
		"no-bitwise": "off",
		"no-buffer-constructor": "off",
		"no-caller": "off",
		"no-case-declarations": "error",
		"no-catch-shadow": "off",
		"no-class-assign": "error",
		"no-compare-neg-zero": "error",
		"no-cond-assign": "error",
		"no-confusing-arrow": ["error", {
			"allowParens": false
		}],
		"no-console": "off",
		"no-const-assign": "error",
		"no-constant-condition": "error",
		"no-continue": "off",
		"no-control-regex": "error",
		"no-debugger": "error",
		"no-delete-var": "error",
		"no-div-regex": "off",
		"no-dupe-args": "error",
		"no-dupe-class-members": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-duplicate-imports": "error",
		"no-else-return": "error",
		"no-empty": "error",
		"no-empty-character-class": "error",
		"no-empty-function": "off",
		"no-empty-pattern": "error",
		"no-eq-null": "off",
		"no-eval": "off",
		"no-ex-assign": "error",
		"no-extend-native": "off",
		"no-extra-bind": "off",
		"no-extra-boolean-cast": "error",
		"no-extra-label": "off",
		"no-extra-parens": "off",
		"no-extra-semi": "error",
		"no-fallthrough": "error",
		"no-floating-decimal": "off",
		"no-func-assign": "error",
		"no-global-assign": "error",
		"no-implicit-coercion": "off",
		"no-implicit-globals": "error",
		"no-implied-eval": "off",
		"no-inline-comments": "off",
		"no-inner-declarations": "error",
		"no-invalid-regexp": "error",
		"no-invalid-this": "off",
		"no-irregular-whitespace": "error",
		"no-iterator": "off",
		"no-label-var": "off",
		"no-labels": "off",
		"no-lone-blocks": "off",
		"no-lonely-if": "error",
		"no-loop-func": "off",
		"no-magic-numbers": "off",
		"no-mixed-operators": "error",
		"no-mixed-requires": "off",
		"no-mixed-spaces-and-tabs": ["error", "smart-tabs"],
		"no-multi-assign": "error",
		"no-multi-spaces": "error",
		"no-multi-str": "off",
		"no-multiple-empty-lines": "off",
		"no-native-reassign": "off",
		"no-negated-condition": "off",
		"no-negated-in-lhs": "off",
		"no-nested-ternary": "off",
		"no-new": "off",
		"no-new-func": "off",
		"no-new-object": "error",
		"no-new-require": "off",
		"no-new-symbol": "error",
		"no-new-wrappers": "error",
		"no-obj-calls": "error",
		"no-octal": "error",
		"no-octal-escape": "off",
		"no-param-reassign": "off",
		"no-path-concat": "error",
		"no-plusplus": "off",
		"no-process-env": "off",
		"no-process-exit": "off",
		"no-proto": "off",
		"no-prototype-builtins": "off",
		"no-redeclare": "error",
		"no-regex-spaces": "error",
		"no-restricted-globals": "off",
		"no-restricted-imports": "off",
		"no-restricted-modules": "off",
		"no-restricted-properties": "off",
		"no-restricted-syntax": "off",
		"no-return-assign": "error",
		"no-return-await": "off",
		"no-script-url": "off",
		"no-self-assign": "error",
		"no-self-compare": "off",
		"no-sequences": "off",
		"no-shadow": "off",
		"no-shadow-restricted-names": "off",
		"no-spaced-func": "off",
		"no-sparse-arrays": "error",
		"no-sync": "off",
		"no-tabs": "off",
		"no-template-curly-in-string": "off",
		"no-ternary": "off",
		"no-this-before-super": "error",
		"no-throw-literal": "error",
		"no-trailing-spaces": "error",
		"no-undef": "error",
		"no-undef-init": "off",
		"no-undefined": "off",
		"no-underscore-dangle": "off",
		"no-unexpected-multiline": "error",
		"no-unmodified-loop-condition": "off",
		"no-unneeded-ternary": "error",
		"no-unreachable": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unused-expressions": "error",
		"no-unused-labels": "error",
		"no-unused-vars": "error",
		"no-use-before-define": "off",
		"no-useless-call": "off",
		"no-useless-computed-key": "error",
		"no-useless-concat": "off",
		"no-useless-constructor": "error",
		"no-useless-escape": "error",
		"no-useless-rename": "error",
		"no-useless-return": "off",
		"no-var": "error",
		"no-void": "off",
		"no-warning-comments": "off",
		"no-whitespace-before-property": "error",
		"no-with": "off",
		"nonblock-statement-body-position": "off",
		"object-curly-newline": "off",
		"object-curly-spacing": ["error", "never"],
		"object-property-newline": "off",
		"object-shorthand": "off",
		"one-var": "off",
		"one-var-declaration-per-line": "off",
		"operator-assignment": "error",
		"operator-linebreak": ["error", "after"],
		"padded-blocks": ["error", "never"],
		"padding-line-between-statements": "off",
		"prefer-arrow-callback": "off",
		"prefer-const": "error",
		"prefer-destructuring": "off",
		"prefer-numeric-literals": "off",
		"prefer-promise-reject-errors": "error",
		"prefer-reflect": "off",
		"prefer-rest-params": "off",
		"prefer-spread": "off",
		"prefer-template": "error",
		"quote-props": ["error", "consistent-as-needed"],
		"quotes": ["error", "single"],
		"radix": "error",
		"require-await": "error",
		"require-jsdoc": "off",
		"require-yield": "error",
		"rest-spread-spacing": ["error", "never"],
		"semi": ["error", "always"],
		"semi-spacing": ["error", {
			"before": false,
			"after": true
		}],
		"semi-style": "off",
		"sort-imports": "off",
		"sort-keys": "off",
		"sort-vars": "off",
		"space-before-blocks": "error",
		"space-before-function-paren": ["error", {
			"anonymous": "always",
			"named": "never",
			"asyncArrow": "ignore"
		}],
		"space-in-parens": ["error", "never"],
		"space-infix-ops": "error",
		"space-unary-ops":  [2, {
			"words": true,
			"nonwords": false
		}],
		"spaced-comment": "off",
		"strict": "error",
		"switch-colon-spacing": "off",
		"symbol-description": "off",
		"template-curly-spacing": "error",
		"template-tag-spacing": "off",
		"unicode-bom": "error",
		"use-isnan": "error",
		"valid-jsdoc": "off",
		"valid-typeof": "error",
		"vars-on-top": "off",
		"wrap-iife": "off",
		"wrap-regex": "off",
		"yield-star-spacing": "off",
		"yoda": "off"
	}
}
